name: Auto Codeowners

on:
  schedule:
    # Run at 12:00 UTC everyday
    - cron: "0 12 * * *"
  workflow_dispatch:
    
jobs:
  auto-codeowners:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygithub
      - name: Run Auto Codeowners
        run: |
          python ./auto-codeowners/auto-codeowners.py ${{secrets.APPSEC_GH_TOKEN}}
