name: Snyk Auto Import

on:
  schedule:
    # Run at 11:00 UTC everyday
    - cron: "0 11 * * *"
  workflow_dispatch:
    
jobs:
  snyk-auto-import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygithub
      - name: Run Snyk Auto Importer
        run: |
          python ./snyk-auto-importer/snyk-auto-importer.py ${{secrets.APPSEC_GH_TOKEN}} ${{secrets.SNYK_TOKEN}}
